const PROJECT='salvame-las-papas-cdelu';
const API_KEY='AIzaSyAE8kEBAzDbPvCCD1KCyjq67iFl3dvthLM';
function valor(v){if(!v||typeof v!=='object')return null;if('stringValue'in v)return v.stringValue;if('booleanValue'in v)return v.booleanValue;if(v.arrayValue)return(v.arrayValue.values||[]).map(valor);if(v.mapValue)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,valor(x)]));return null}
async function doc(path){const r=await fetch(`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/${path}?key=${API_KEY}`);if(!r.ok)return null;const j=await r.json();return Object.fromEntries(Object.entries(j.fields||{}).map(([k,v])=>[k,valor(v)]))}
module.exports=async(req,res)=>{
 const c=String(req.query.c||''),p=String(req.query.p||''),i=Math.max(0,Math.min(3,Number(req.query.i||0)));
 if(!/^[A-Za-z0-9_-]{1,160}$/.test(c)||!/^[A-Za-z0-9_-]{1,160}$/.test(p))return res.status(400).end();
 try{const [com,prod]=await Promise.all([doc(`comercios/${c}`),doc(`comercios/${c}/productos/${p}`)]);if(!com||!prod||com.estado!=='activo'||prod.disponible===false)return res.status(404).end();const fotos=Array.isArray(prod.fotos)?prod.fotos.filter(Boolean):(prod.foto?[prod.foto]:[]),src=fotos[i]||fotos[0]||com.fotoPortada||com.logo;if(!src)return res.redirect(302,'/icon-512.png');res.setHeader('Cache-Control','public, max-age=86400, s-maxage=86400');if(/^data:image\/(png|jpeg|jpg|webp);base64,/i.test(src)){const m=src.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/i),tipo=m[1].toLowerCase()==='jpg'?'jpeg':m[1].toLowerCase();res.setHeader('Content-Type','image/'+tipo);return res.status(200).send(Buffer.from(m[2],'base64'))}if(/^https?:\/\//i.test(src))return res.redirect(302,src);return res.status(404).end()}catch(e){console.error(e);return res.status(500).end()}
};
